### PR TITLE
Fix numerous typos using codespell

### PR DESCRIPTION
**Pull request by yarikoptic**
note -- this is just a single commit from a full(er) collection which was proposed in https://github.com/MouseLand/suite2p/pull/1006 and carried configuration for codespell and also github action.

This commit is just typo fixes done by codespell when it had that config.

### CODE REVIEW

**Comment by marius10p** [comment]
Thanks, but we don't accept this kind of pull request.

**Comment by yarikoptic** [comment]
I am confused -- could you elaborate on what is wrong with a PR contributing fixing typos?  or what kinds of PRs you do accept?

**Comment by marius10p** [comment]
We accept contributions which solve significant existing problems. Nothing from automated code checkers please, they're too likely to introduce errors. Thanks.

**Comment by yarikoptic** [comment]
I will rest my case here to save all of us time and effort.

**Pull request closed without merging**
