### PR TITLE
Circimports

### PR DESCRIPTION
**Pull request by nickdelgrosso**
Hi, 

This pull request represents steps 1-3.5 in the import refactoring process described in Issue #349.  It also includes PyDep scripts for visualizing suite2p's dependency structure, including highlighting dependency cycles.

Best wishes,

Nick

### CODE REVIEW

**Comment by carsen-stringer** [comment]
based on the graph it looks like sourcery is being called preferentially somehow? sparsedetect will be the main module going forward, there just isn't any documentation on it yet. otherwise looks good!

**Comment by nickdelgrosso** [comment]
Thanks!  Yes, the graph shows that the sourcery.py module currently depends on the  sparsedetect.py module.  If this shouldn't be the case (which it sounds like), then further refactoring should ensure that the two modules are not dependent on each other.  

On inspection, it looks like it's just the SVD functions that are shared between the two.  To resolve it, I'll make a new module (detection.svd) that sourcery and sparsedetect import from.

**Comment by carsen-stringer** [comment]
oh I misunderstood the graph, awesome, actually I think it's just the bin function that is used by both (sourcery should be the only one that takes an SVD)

**Comment by nickdelgrosso** [comment]
Okay, great!  I've done the refactor to seperate them out (commit 
88369ab).  Do you see other dependencies that should be changed?

**Comment by nickdelgrosso** [comment]
When finished, the graph should look very clean (almost like an org chart in a business), with all arrows pointing downward and all modules closely clustered together (submodules above packages, packages above main() entrypoints and scripts)

**Comment by nickdelgrosso** [comment]
The extraction and detection subpackages seem particularly intertwined.  Would it be problematic to merge them into a single subpackage?   There aren't currently any docs tutorials that explain extraction as seperate from detection, so it wouldn't break any docs.

**Comment by carsen-stringer** [comment]
I think it's a good idea to merge them, thanks!

**Comment by nickdelgrosso** [comment]
Done.  The graph is starting to look nicer--the sequential nature steps in the pipeline are even starting to become apparent!

**Pull request merged**
