### PR TITLE
Loading plugins

### PR DESCRIPTION
**Pull request by hrouault**
It is done through the entry point mechanism.
All the plugins have a line in the Plugins menu. Each entry point
consists of a class with the objects .name, .menu, .window()

### CODE REVIEW

**Comment by carsen-stringer** [comment]
Looks good to me, I just don't understand how it is going to work. Is your plan is to make the plugin files in the suite2p repository? Or will they come from the package manager? This seems like a nice way to avoid having to write a new menu item for each one.

**Comment by hrouault** [comment]
> Looks good to me, I just don't understand how it is going to work. Is your plan is to make the plugin files in the suite2p repository? Or will they come from the package manager? This seems like a nice way to avoid having to write a new menu item for each one.

You could add plugins in the repository itself (like even the visualizer, etc). But it also allows putting plugins in different packages.

Note that I didn't fully test the code in PR... I hope it won't break anything. I'll let you know as soon as the plugin I am writing is functional.

**Comment by carsen-stringer** [comment]
It didn't break anything when I tested it :) that's cool that it will work with both. We will include your plugin in the repo and maybe after you're done you could write a short wiki doc explaining how someone can make their own and that they can refer to your layout.

**Comment by hrouault** [comment]
> [...]after you're done you could write a short wiki doc explaining how someone can make their own and that they can refer to your layout.

Sure!

**Pull request merged**
