### PR TITLE
Add manual labelling with NWB

### PR DESCRIPTION
**Pull request by kir0ul**
An attempt to fix https://github.com/MouseLand/suite2p/issues/437

### CODE REVIEW

**Comment by carsen-stringer** [comment]
thanks for taking a stab at this, help is certainly appreciated!! but implemented this way the NWB is saved each time a cell is swapped, which would slow down the swapping process for large. I'd recommend saving like the MATLAB button, see function here: https://github.com/MouseLand/suite2p/blob/0858b6ba131105210f60277d05df120a5970d9df/suite2p/gui/io.py#L402

which is added to the file menu here:
https://github.com/MouseLand/suite2p/blob/0858b6ba131105210f60277d05df120a5970d9df/suite2p/gui/menus.py#L42

you will never lose your progress because `iscell.npy` is always saved.

**Comment by kir0ul** [comment]
100% agree, thanks for the pointers, I'll have look at that!

**Comment by kir0ul** [comment]
Is it better this way? Not sure how to do that but should I test the new menu button in some way?
Also I added a couple of tests on the `save_nwb()` function.

**Comment by kir0ul** [comment]
I changed this PR in draft because I noticed if I reopen the NWB file previously saved with some manual labeling, the changes didn't appear in the GUI, so maybe there's something wrong. I'll try to have a look when I have a bit more time.

**Comment by kir0ul** [comment]
If I wanted to add an NWB file in the `test_data` folder, what would be the best way to do that? Can I just throw it in the Git repository or should I use DVC to do that?

**Comment by carsen-stringer** [comment]
@nickdelgrosso can help you with NWB setup. I don't think we're going to be able to have an automated test for a GUI feature like this though, again @nickdelgrosso knows more about pyqt testing

**Comment by kir0ul** [comment]
Nevermind, that's indeed what I had in mind but after checking how `pytest-qt` works and what others do on PyQt based projects, I agree it's overkill :smile:

**Comment by kir0ul** [comment]
That seems to work according to a few use cases I tried so I guess this is ready for review. I kind of had a hard time with paths in switching between NWB and NumPy file formats with the GUI. I came up with some solutions but not sure those are the best, so I'm happy to take any comments.

**Comment by carsen-stringer** [comment]
thanks this looks good to me, can you remove your tests which have absolute paths to your data?

**Comment by carsen-stringer** [comment]
FYI we do have a test for NWB it's in tests/regression/test_full_pipeline.py

**Comment by carsen-stringer** [comment]
I removed one of your tests with local paths but kept the others because they are working correctly I think, thanks

**Comment by kir0ul** [comment]
Thanks for accepting my PR!

> I removed one of your tests with local paths but kept the others because they are working correctly I think, thanks

Sorry I haven't been more responsive on this, but those are not local paths, only some strings I made up to test the [`get_suite2p_path()`](https://github.com/MouseLand/suite2p/blob/main/suite2p/io/utils.py#L295) function. I would strongly suggest to revert this commit: https://github.com/MouseLand/suite2p/commit/1e5feb86f566c4a636046f5ea74547564b42701e, otherwise the [`get_suite2p_path()`](https://github.com/MouseLand/suite2p/blob/main/suite2p/io/utils.py#L295) function is not tested.
I can do a follow up PR to do this if you'd like!

**Pull request merged**
