### PR TITLE
Improve NWB support

### PR DESCRIPTION
**Pull request by kir0ul**
This PR does the following:
- Save `F_chan2` and `Fneu_chan2` to NWB (fixes https://github.com/MouseLand/suite2p/issues/817),
- Add planes fluorescence containers to NWB,
- Separate ROIs for each plane in NWB,
- Test round trip writing + reading NWB file.

Here are below some screenshots that show the structure differences of the resulting NWB file (left: before this PR, right: after this PR): 

image image

### CODE REVIEW

**Comment by kir0ul** [comment]
Fixed the merge conflicts, but not sure why there's a segmentation fault on MacOS as tests run fine on my Linux machine.

cc @rly

**Comment by chriski777** [comment]
Hey @kir0ul, thanks for this PR. Ah, yep the segmentation fault error on the Mac happens for some reason with the latest version of PyTorch. I'll take a look at this PR and try to merge it soon!

**Comment by kir0ul** [comment]
@chriski777 @rly Tests are ok now :heavy_check_mark: so I think this is finally ready for review! :slightly_smiling_face:

**Comment by chriski777** [comment]
@kir0ul, sorry for the late reply! Looks great to me so I'll merge it! Thanks!!!

**Pull request merged**
