### PR TITLE
Optionally use skcuda.fft as a replacement for numpy.fft

### PR DESCRIPTION
**Pull request by neurodroid**
This patch provides optional support for the [scikit-cuda interface to cuFFT](https://scikit-cuda.readthedocs.io/en/latest/reference_fft.html). If `register_binary` is called with `use_cuda=True`, `skcuda.fft` will be used instead of `numpy.fft` if pycuda and scikit-cuda are installed on the system. For debugging, `TEST_CUDA` can be set to `True` in `cuda_utils.py` to compare the results of `skcuda.fft` with `numpy.fft`.
Performance depends on `num_workers` and `batch_size`. On the system used for testing, the sweet spot was somewhere around `batch_size=128` and `num_workers=6`.
There's probably quite a bit of room for further performance improvements.

### CODE REVIEW

**Comment by marius10p** [comment]
Sweet! I'm surprised it still requires multiple CPU workers. We'll test this soon.

**Comment by marius10p** [comment]
What OS, CPU and GPU are you on and what kind of speedups are you getting? On Win10, using this skcuda.fft and multiprocessing parallelism does not work, or it takes a very, very long time. For single worker, it is almost twice slower than the CPU version with multiprocessing. There is also an error when setting TEST_CUDA to True:

    npfft = fft.fft2(x)
NameError: name 'fft' is not defined

**Comment by neurodroid** [comment]
Fixed the missing import.
On ubuntu 16.04, Xeon E5-2640 v4 (10 cores), Quadro M4000, CUDA 9.1, speedup is at best 10% with the skcuda version. That's not much of an improvement, but then again it's a relatively slow GPU, and the code is not optimized. For example, the fft plans are regenerated from scratch for each fft. Priority was to reproduce the numpy.fft results over speed.
Not sure what's going on on Windows. Will try to test if I get my hands on a PC.

**Comment by neurodroid** [comment]
Looking at the latest commit 913457e7e3bcd1a0f674b838bef07bff5a074440 to master, merging would be messy as the ffts are now spread across several files. Given the issues with Windows, I suggest we delete this branch and get back to it once we've sorted out the performance issues on Windows.

**Comment by marius10p** [comment]
Let's leave this branch for now so I have some example code to follow when I get some time to try different CUDA fft approaches. 

Indeed, I wouldn't have expected a big speedup on M4000 compared to a 10-core CPU, but I couldn't even get a speedup on the Titan Volta, so I think something is suboptimal. Needs more testing.

**Comment by carsen-stringer** [comment]
I recently tried again, this time with [cupy](https://cupy.chainer.org/). But still wasn't getting good speed ups - I think I'd have to get cuda jit working. We've found mkl_fft is really quite fast when you run it correctly (loops instead of array ffts, in-place operations, pre-casting variables). I'd also recommend using Ubuntu if you have a choice.

**Pull request closed without merging**
