### PR TITLE
added sbxmap to the repository

### PR DESCRIPTION
**Pull request by rajatsaxena**
Tasks finished:
- added `sbxmap.py` (utility to load the sbx data as numpy array). 
- added basic GUI layout (no functionality yet) for the scanbox 
- added some parts to the `sbx_to_binary` function

Tasks remaining:
- finalizing the `sbx_to_binary` function
- getting the entire GUI up and running 

The scanbox people have a python but it separates the channel: https://scanbox.org/2016/09/02/reading-scanbox-files-in-python/

Capture

### CODE REVIEW

**Comment by rajatsaxena** [comment]
Tasks remaining:

getting the ops['meanImg'] and finishing up all the operations of converting sbx loaded array for further processing

**Comment by carsen-stringer** [comment]
hey raj is this ready to be pulled in? I will make contrast sliders for the mean image too soon, so things should be easier to see (saw your changes to plotting)

**Comment by rajatsaxena** [comment]
I still have not finalized the scanbox to binary file conversion script, that might take me some time.

**Comment by nickdelgrosso** [comment]
Closing due to inactivity.  If you would like to re-submit this feature for the current version of suite2p, please do so in a new pull request.

**Pull request closed without merging**
