### PR TITLE
DVC New Cloud-supported Google Drive Remote

### PR DESCRIPTION
**Pull request by nickdelgrosso**
This pull request is about adding monitoring and usage controls to the dvc remote, so we don't hit the same "usage limit" error we encountered yesterday.  Following the directions on the DVC documentation [here](https://dvc.org/doc/user-guide/setup-google-drive-remote), the dvc database has been migrated to a new remote.  Extra benefits:
  - A special read-only "service account" has been created for travis, that doesn't collide with the normal developer login (we had read-only before, but through a different mechanism).  
  - No fiddling with Travis encryption.
  - Pull requests across repos should work (we can run tests on community submissions now)
  - Usage monitoring and raising if needed.  Shouldn't be a problem, but if we start hitting limits we'll understand why.

To use it, I recommend everyone update dvc (`pip install --upgrade dvc`) to the latest version (they had a 1.0 release recently) and delete the json file so google asks to re-authenticate on the next `dvc pull`.  From there it should work as before.

### CODE REVIEW

**Comment by chriski777** [comment]
This is awesome! Will community developers still be able to call `dvc pull` without authenticating?

**Comment by nickdelgrosso** [comment]
Yes, if they pull from the travis repo: ``dvc pull -r gdrive-travis``

**Comment by nickdelgrosso** [comment]
Two more commits to fix some quality-of-life issues:

  - I just did a little more digging through the monitor and found the source of the "usage exceeded" error: DVC was making way too many calls at once for google drive.  The DVC devs [reccomend just tracking a whole folder](https://dvc.org/doc/command-reference/add#tracking-directories)  when big data directories are involved, in order to have fewer calls and to more-efficiently do downloads and uploads.  
  - Also, every time we changed branches, pull/pushed, or commited, DVC would add a "/tmp" line to its .gitignore file.  Very annoying to stash it every time we want to make a change!  This is a [well-known issue](https://github.com/iterative/dvc/issues/3561) for certain repos that the devs weren't able to track down the source of, but have somehow fixed for new repos.  They recommend just re-initializing the repo with the latest DVC version.

To fix this, I re-initialized the DVC repo.  You'll notice that there's now only one .dvc file (which tracks the data/testdata folder as a whole), and hopefully that that .gitignore problem is gone!

**Comment by nickdelgrosso** [comment]
Okay __now__ the .gitignore:/tmp issue is fixed.  Seems to be because a credentials file was committed to the .dvc/tmp directory.  Moving it to .dvc/cred stopped the .gitignore:/tmp behavior

**Comment by carsen-stringer** [comment]
lol probably my file :D I was being lazy with the stashing of the dvc folder -- thanks nick this is merged! I will make the ``dvc pull -r gdrive-travis`` the default instructions in the readme

**Pull request merged**
