### PR TITLE
use chan field if exists

### PR DESCRIPTION
**Pull request by orena1**
If chan exists in info it already contains the number of channels
I don't understand exactly the other conditions, but anyway, the pull request just aligns better with the official MATLAB code.

https://github.com/vazirilab/neurolabware_scanbox_utils_docs/blob/326dff0883b1861ba499099ed36a5aba4cbefb0f/src/sbxread_all.m#L79

### CODE REVIEW

**Comment by orena1** [comment]
Another option is to use this:
https://github.com/MouseLand/suite2p/pull/619

**Comment by marius10p** [comment]
I am not familiar with the scanbox reader, but I think chan was supposed to be an index for the green channel for functional analysis. The number of channels would presumably be specified separately? @carsen-stringer

**Comment by orena1** [comment]
Hi, @marius10p if you look at the original matlab implementation you can see that the line I added was missing from the python implementation that you are using:
https://github.com/vazirilab/neurolabware_scanbox_utils_docs/blob/326dff0883b1861ba499099ed36a5aba4cbefb0f/src/sbxread_all.m#L79

It is a bit hard for me to understand the MATLAB code as I think it contains a lot of backward compatibilities if/else, but I added this "missing" line to my suite2p and it managed to load the data correctly.

**Comment by carsen-stringer** [comment]
can you try the latest version of suite2p + the new sbxreader package that @jcouto wrote? please put an issue on his github if there are problems because we do not know how scanbox works :)

**Comment by orena1** [comment]
Hi @carsen-stringer, yes @jcouto package works great (as I suggested here:https://github.com/MouseLand/suite2p/pull/564#issuecomment-777799897)
Thanks

**Pull request closed without merging**
