### PR TITLE
added pipeline Test with sourcery coverage

### LINKED ISSUE #367: test_pipeline tests have low coverage.
The current coverage stats show clearly that we only inter-tester reliability for about 25% of the code.  This includes the gui, though, which isn't part of our short-term change plans.  Probably it's closer to 40%.  

https://coveralls.io/github/nickdelgrosso/suite2p

If we can get the amount of non-gui code to be >80% covered by the test_pipeline functions (basiclaly, by calling run_s2p() with different settings in ops), then we'll know that that code doesn't include any simple bugs (NameError, SyntaxError, AttributeError, etc--), and that any refactoring we do is likely to be checked for them.  At that stage, we'll have a good regression test going and can more safely perform refactoring without introducing run_s2p-breaking bugs that will have immediate impacts on users.

### PR DESCRIPTION
**Pull request by nickdelgrosso**
Closes #367 

Hi,

This test uses the `ops['sparse_mode']=0 ` setting suggested in https://github.com/MouseLand/suite2p/issues/367#issuecomment-637592726

I wasn't able to see a nice way to name the test data directory, though, so I just relied on the check_output function to use the channel number and frame count.  Having the data in a "sourcery" directory would be nice, though, as would moving it to a module-level test.  Any revisions that make that happen would be much appreciated!

Best wishes,

Nick

### CODE REVIEW

**Comment by nickdelgrosso** [comment]
Not compatible with other tests--removed data was required.  Closing and revising in a new pull request.

**Comment by nickdelgrosso** [comment]
Okay, fixed

**Comment by nickdelgrosso** [comment]
Note: this builds on pull request #386 , so that should be checked and merged before this one.

**Comment by chriski777** [comment]
Merged #386. The added sorcery test and test_data look good to me! WIll merge this too.

**Pull request merged**
