### PR TITLE
Refactors: run_s2p.py conditionals

### PR DESCRIPTION
**Pull request by nickdelgrosso**
This set of refactors simplifies run_s2p.py by removing complexity from some extraneous if-statements, removing resulting unused intermediate variables, and removing duplicated code between multiple conditional branches.

### CODE REVIEW

**Comment by chriski777** [comment]
Changes look good! There seems to be a problem with this commit 8cba2d406234f88dadb7a7e2b3ee8aa6971d2416 however when you run suite2p again on suite2p-processed data. 

```
>>>ERROR<<<
    if all(map(Path.is_file, chain(ops_paths, *[Path(f).glob('data*.bin') for f in plane_folders]))):
  File "/Users/chriski/opt/anaconda3/envs/suite2p/lib/python3.7/pathlib.py", line 1382, in is_file
    return S_ISREG(self.stat().st_mode)
AttributeError: 'str' object has no attribute 'stat'
Interrupted by error (not finished)
```

**Comment by nickdelgrosso** [comment]
Ah, it's because the ops_paths were strings, Path.is_file() only accepts Path objects.  Switching to os.path.isfile() fixes it.  Great catch, @chriski777 !

How can we make a test case to catch this in the future?

**Comment by chriski777** [comment]
Hmm, so for this one, I think the simplest test case involves running `run_s2p` twice with the same ops.

**Comment by nickdelgrosso** [comment]
Added the "run test twice" condition.  Because pipeline tests are slow, just modified the "2plane_2chan" test to run twice instead of adding a new test that runs twice.

**Comment by chriski777** [comment]
The added test runs fine on my machine! If the time it takes for the second run is a concern and you'd like to just check for the error above, we could set `do_registration` to 0 and roidetect/spikedect to false. The second run doesn't seem to take too long on travis (~20s) though so we could keep it too. Having a second run in general might also just be good to have.

**Comment by nickdelgrosso** [comment]
Okay, sounds like it works out then!  Merging.

**Pull request merged**
