### PR TITLE
nd2 support

### PR DESCRIPTION
**Pull request by tdincer**
This PR introduces a `nd2_to_binary` converter, which allows users to feed their Nikon `nd2` files directly to `suite2p` without converting them into `tif` files. This saves disk space! To run the converter, the user only has to set `ops['input_format'] = 'nd2'`.

The changes in this PR are tested by running the suite2p on the `nd2` and `tif` format of the same dataset. The calcium activities (`F.npy`) from these two data formats are found to be identical.

### CODE REVIEW

**Comment by tdincer** [comment]
This PR address the enhancement in https://github.com/MouseLand/suite2p/issues/800

**Comment by carsen-stringer** [comment]
thanks for the PR, it looks great. I'm a bit confused though, why did "tiff.py" have to change? Many of the lines are changed in that function. Likewise there are many changes in run_s2p.py that are unnecessary. Maybe it's the blackify commit? Those sorts of changes are not accepted because it makes it difficult for us to track actual changes to the code over time

**Comment by tdincer** [comment]
> thanks for the PR, it looks great. I'm a bit confused though, why did "tiff.py" have to change? Many of the lines are changed in that function. Likewise there are many changes in run_s2p.py that are unnecessary. Maybe it's the blackify commit? Those sorts of changes are not accepted because it makes it difficult for us to track actual changes to the code over time

I totally forgot about this PR. I was just fixing a small issue in `nd2.py` to avoid a potential memory leakage issue. Yes, most of the changes are because of the blackify commit. My text editor formatted the code with Black.

As far as I remember, `tiff.py` has some changes regarding `ScanImageTiffReader` as we were having issues with it. The rest should be formatting.

If there is a chance of this PR getting merged, I can revert the code to that of March 7 (https://github.com/MouseLand/suite2p/pull/809/commits/bc85d6d7da6a35dec9fc13ccb2ba2d07862f4675) and reapply the rest of the non-formatting changes.

**Comment by carsen-stringer** [comment]
yes this seems like a useful PR that doesn't mess with anything internal to suite2p, so we'd be happy to accept it if you revert as you said. sorry for the delayed response here

**Comment by tdincer** [comment]
Thank you! I'm closing this PR. Please see the other nd2 support PR.

**Pull request closed without merging**
