### PR TITLE
bugfix: ufunc cast error when loading bruker files

### LINKED ISSUE #545: Input format error
Hello,
I updated to the current version of Suite2p and I’m now unable to load tiffs under the bruker input_format option. If I concatenate frames and run with tiff input_format the pipeline runs normally. Loading tiffs under the bruker input_format option wasn’t an issue with my previous versions of Suite2p. Please see error below.
Thanks!

** Found 6000 tifs - converting to binary **
>>>ERROR<<<
Traceback (most recent call last):
  File "…suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "…suite2p\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "…suite2p\__main__.py", line 78, in <module>
    main()
  File "…suite2p\__main__.py", line 71, in main
    run_s2p(ops, db)
  File "…suite2p\run_s2p.py", line 372, in run_s2p
    ops0 = convert_funs[ops['input_format']](ops.copy())
  File "…suite2p\io\tiff.py", line 402, in ome_to_binary
    ops1[ix]['meanImg'] += im
TypeError: Cannot cast ufunc add output from dtype('int32') to dtype('uint16') with casting rule 'same_kind'
Interrupted by error (not finished)

### PR DESCRIPTION
**Pull request by nickdelgrosso**
Closes #545 , adds test coverage to `io.tiff.ome_to_binary()`

### CODE REVIEW

**Comment by marysethomas** [comment]
Hi @nickdelgrosso! I believe I am experiencing this bug. Any idea when the code will be merged?

Thanks!

Maryse

**Comment by nickdelgrosso** [comment]
Good question.  I'll merge it now.

**Comment by nickdelgrosso** [comment]
@marysethomas If you'd like to use this code before the next release, you'll have to clone it from the dev branch, which contains the latest changes.

Best wishes,

Nick

**Comment by marysethomas** [comment]
Thank you @nickdelgrosso It seems to be working!

**Pull request merged**
