### PR TITLE
Modified __main__ script so it works with benchmark script

### PR DESCRIPTION
**Pull request by chriski777**
I made some edits so that the `__main__.py` script is compatible with the changes in b815340afe02a21f927fc7f7453f2f9ba4ffe30b. I added back the changes involving `add_args` and `parse_args` since the benchmark script relies on those functions to run properly. I've checked and made sure that these changes don't break the GUI.

### CODE REVIEW

**Comment by carsen-stringer** [comment]
sorry this is still not working for me -- I set a parameter like "spatial_scale" = 1 in the GUI and then I go to run it and the main function reverts it to zero
image

**Comment by chriski777** [comment]
ah yes, I saw the message on the commit and realized I didn't really check if changing the parameters worked properly.

**Comment by nickdelgrosso** [comment]
Looks good!  Merged

**Comment by chriski777** [comment]
@carsen-stringer the commits above take care of the issue with the ops parameters not being set.

**Pull request merged**
