### PR TITLE
nd2 support

### PR DESCRIPTION
**Pull request by tdincer**

### CODE REVIEW

**Comment by tdincer** [comment]
@carsen-stringer Here is a clean version of the nd2 io feature. 

I'm just pasting the note from https://github.com/MouseLand/suite2p/pull/809

> This PR introduces a nd2_to_binary converter, which allows users to feed their Nikon nd2 files directly to suite2p without converting them into tif files. This saves disk space! To run the converter, the user only has to set ops['input_format'] = 'nd2'.
> 
> The changes in this PR are tested by running the suite2p on the nd2 and tif format of the same dataset. The calcium activities (F.npy) from these two data formats are found to be identical.

**Comment by tdincer** [comment]
Hi @carsen-stringer - Would you be able to review the PR? I'd be happy to quickly apply any changes you might suggest.

**Comment by carsen-stringer** [comment]
Thanks so much @tdincer! Can you please add nd2 as a dependency in the setup.py? Also can you please add a brief statement here about nd2 if you have time: https://github.com/MouseLand/suite2p/blob/main/docs/inputs.rst#different-file-types.

Then @chriski777, once this is done, can you please review this PR? (run tests)

**Comment by chriski777** [comment]
Hi @tdincer, could you also add `nd2` as a dependency on the setup.py of your branch? That seems to be why the tests are failing

**Comment by tdincer** [comment]
> Hi @tdincer, could you also add `nd2` as a dependency on the setup.py of your branch? That seems to be why the tests are failing

@chriski777  I added `nd2` to `setup.py` and improved the data dimension sorting. The tests should be successful now.

**Comment by chriski777** [comment]
Awesome, @tdincer, thanks a bunch! Changes have been merged.

**Pull request merged**
